test: &default

  # Credentials for REST APIs
  client_id: AYfa2Y2U5stUn4XeR2cF6DIXTKt910KpDnFhRXpDus2wXKccDxmk38h4GqpFI-pKNUNUzER_K40r-CHH
  client_secret: EDpsT8td2s-QfneftWUXxp4a0m3LF8EMml-8odWfXk1hhuwOGvQXj8i5RuO8o_6_QQI4QyCnUmPqVf86

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  app_id: APP-80W284485P519543T
  username: jb-us-seller_api1.paypal.com
  password: WX4WTU3S8MY44S7F
  signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  sandbox_email_address: seller@digitalnomad.com


  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

development:
  <<: *default

production:
  <<: *default
  mode: live
